AccountBook/Controllers/ListController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AccountBook.Models;

namespace AccountBook.Controllers
{
    public class ListController : Controller
    {

        private readonly MyContext _context;

        /// <summary>
        /// 必要な項目をインクルードした一覧表示用のデータ。
        /// </summary>
        private Task<List<PaymentHeader>> paymentHeadersAsync
        {
            get
            {
                return _context.paymentHeaders.Include(elem => elem.User).ToListAsync();            
            }
        }
         

        public ListController(MyContext context)
        {
            _context = context;
        }


        // GET: PaymentHeaders
        public async Task<IActionResult> Index()
        {
            return View(await paymentHeadersAsync);
        }

        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            //コンテキストから、その情報を取得する
            var data = _context.paymentHeaders.Where(elem => elem.PaymentHeaderId == id)
                .Include(elem => elem.PaymentDetails).FirstOrDefault();

            if (data == null)
            {
                return NotFound();
            }

            return View(data);
        }

        // GET: PaymentHeaders/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: PaymentHeaders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,PaymentName,PaymentMonth,ActuialPaymentMonth,DataCreatedDate,DataUpdateDate,Memo,MoneyAmount")] PaymentHeader paymentHeader)
        {
            if (ModelState.IsValid)
            {
                _context.Add(paymentHeader);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(paymentHeader);
        }

        // GET: PaymentHeaders/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var paymentHeader = await _context.paymentHeaders.FindAsync(id);
            if (paymentHeader == null)
            {
                return NotFound();
            }
            return View(paymentHeader);
        }

        // POST: PaymentHeaders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,PaymentName,PaymentMonth,ActuialPaymentMonth,DataCreatedDate,DataUpdateDate,Memo,MoneyAmount")] PaymentHeader paymentHeader)
        {
            if (id != paymentHeader.PaymentHeaderId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(paymentHeader);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PaymentHeaderExists(paymentHeader.PaymentHeaderId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(paymentHeader);
        }

        // GET: PaymentHeaders/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var paymentHeader = await _context.paymentHeaders
                .FirstOrDefaultAsync(m => m.PaymentHeaderId == id);
            if (paymentHeader == null)
            {
                return NotFound();
            }

            return View(paymentHeader);
        }

        // POST: PaymentHeaders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var paymentHeader = await _context.paymentHeaders.FindAsync(id);
            _context.paymentHeaders.Remove(paymentHeader);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PaymentHeaderExists(int id)
        {
            return _context.paymentHeaders.Any(e => e.PaymentHeaderId == id);
        }

        [HttpPost]
        public async Task<IActionResult> Search(string searchString)
        {

            var result = await _context.paymentHeaders.Where(elem => elem.PaymentName.Contains(searchString)).ToListAsync();

            return View("Index", result);
        }



    }
}

AccountBook/Views/List/Details.cshtml
@model AccountBook.Models.PaymentHeader

@{
    ViewData["Title"] = "詳細情報の確認 - " + Model.PaymentName;
}


@section CSS{
    <link rel="stylesheet" href="~/css/Detail.css" />
}

<h1>詳細情報の確認 - @Model.PaymentName</h1>

<h2>明細情報</h2>

<div>

    <div>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.PaymentName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.PaymentName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.User.Name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.PaymentMonth)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Memo)
                    </th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                        @Html.DisplayFor(model => model.PaymentName)
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.PaymentName)
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.User.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.PaymentMonth)
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.Memo)
                    </td>
                </tr>
            </tbody>
        </table>
    </div>

    <h2>購入項目一覧</h2>

    <div>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.PaymentDetails.First().PaymentType)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.PaymentDetails.First().ItemName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.PaymentDetails.First().UnitPrice)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.PaymentDetails.First().UnitCount)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.PaymentDetails.First().TaxType)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.PaymentDetails.First().MoneyAmount)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.PaymentDetails.First().Memo)
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var detail in Model.PaymentDetails)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => detail.PaymentType)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => detail.ItemName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => detail.UnitPrice)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => detail.UnitCount)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => detail.TaxType)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => detail.MoneyAmount)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => detail.Memo)
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

</div>

AccountBook/Views/List/Index.cshtml
@model IEnumerable<AccountBook.Models.PaymentHeader>

@{
    ViewData["Title"] = "明細一覧";
}

@section CSS{ 
    <link rel="stylesheet" href="~/css/Index.css" />
}

<h1>明細一覧</h1>

<p>
    <a class="btn btn-primary" asp-action="Create">新しく明細を作成する</a>
</p>


<div>

    @*検索*@
    @using (Html.BeginForm("Search", "List", FormMethod.Post))
    {
        <div class="search-form">
            <div class="search-text">
                <button type="submit" class="search-button" asp-action="Search"></button>
                @*<button type="button" class="search-condition-toggle-collapse"></button>*@
                @Html.TextBox("searchString", "", new { placeholder = "明細名または購入項目名で検索" })
            </div>
        </div>

        <!--<div class="search-Form-Detail" style="height:300px;background-color:red;">-->
        @*詳細検索の入力欄*@
        <!--</div>-->
    }

    <div class="list">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.PaymentName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.PaymentName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.User.Name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.PaymentMonth)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Memo)
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            <a asp-action="Details" asp-route-id="@item.PaymentHeaderId">
                                @Html.DisplayFor(modelItem => item.PaymentName)
                            </a>
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.MoneyAmount)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.User.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.PaymentMonth)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Memo)
                        </td>
                    </tr>
                }
            </tbody>
        </table>

    </div>


    @section Scripts{

        @*明細の検索フォームを構成する*@
        <script src="~/js/components/PaymentSearchForm.js"></script>

    }

</div>